Traceback (most recent call last):
  File "C:/Users/Ryan/Documents/PythonProjects/PyControlledLED/customGUI.py", line 621, in <module>
    vp_start_gui()
  File "C:/Users/Ryan/Documents/PythonProjects/PyControlledLED/customGUI.py", line 32, in vp_start_gui
    top = Toplevel1 (root)
  File "C:/Users/Ryan/Documents/PythonProjects/PyControlledLED/customGUI.py", line 122, in __init__
    _img0 = tk.PhotoImage(file=photo_location)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "C:/Users/Ryan/Documents/PythonProjects/PyControlledLED\../Users/Ryan/Documents/PythonProjects/PyControlledLED/images/steamIcon.png": no such file or directory
